### ISSUE TITLE
Could we use `unreachable` instead?

### ISSUE THREAD

**Issue by mjgpy3** [freckle/exhaustive-js#4]
I just saw [this library](https://www.npmjs.com/package/unreachable) and I was wondering if it's worth exploring instead of maintaining our own.

**Comment by mjgpy3** [comment]
cc @luckysoni

**Comment by luckysoni** [comment]
It seems `unreachable` wouldn't help in the case of reducers for which we have [exhaustiveReducer](https://github.com/freckle/exhaustive-js/pull/1/files?file-filters%5B%5D=.ts&show-viewed-files=true#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R11).

**Comment by mjgpy3** [comment]
I see. Though that only seems to be used in 2 places (and is thus a prime candidate for inlining).

**Comment by luckysoni** [comment]
We will be using unreachable :+1:

**Comment by luckysoni** [comment]
I encountered an issue with `unreachable` and saw that their repo had a [pull request](https://github.com/Gozala/unreachable/pull/1) to remedy the same but the owner never responded for over a month. I unarchived this repository.

**Comment by LinusU** [comment]
@luckysoni I was the one originally suggesting that PR, and when I didn't get a response I published it under the name `ts-unreachable`: https://github.com/LinusU/ts-unreachable
